<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>GlamWire_Case_Cracked</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\Katmo\OneDrive\Desktop\CPW Classes\CPW Adv. Net &amp; Software Dev\Software Project Dev\GLAMWIRE1.0\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\Katmo\OneDrive\Desktop\CPW Classes\CPW Adv. Net &amp; Software Dev\Software Project Dev\GLAMWIRE1.0\.editorconfig" />
  </ItemGroup>

</Project>